title: "Soham's Blog"
description: "A gamified blog about scientific discovery and uncertainty."
baseurl: "" 
url: "https://shb2908.github.io" 

markdown: kramdown
kramdown:
  auto_ids: true
  syntax_highlighter: rouge
  
theme: minima 
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include custom source folder
include: ["_src"]

# Contact Email 
email: "sohamshb9119@gmail.com"  

# Social Links
social:
  twitter: "https://x.com/Besoham2003"
  linkedin: "https://www.linkedin.com/in/soham-bose-2a6a6a250/"
  bluesky: "https://bsky.app/profile/yourusername"
  github: "https://github.com/shb2908"
  scholar: "https://scholar.google.com/citations?user=Hm5_iKMAAAAJ&hl=en" 
  cloud: "" 

contact_form:
  url: "https://docs.google.com/forms/d/e/1FAIpQLSexSzszsyWnMz6BgyML3LOMRbG0N4dHhlCFG9IOmEZSg4AtZg/formResponse"
  entry_name: "entry.2005620554"
  entry_email: "entry.1045781291"
  entry_message: "entry.1065046570"
